### ISSUE TITLE
Some typos & my own ideas

### ISSUE THREAD

**Issue by PMheart** [arslan2012/Lazy-Hackintosh-Image-Generator#1]
Well, there is something wrong with your README.md which is unnecessary. Feel free to close it.
1. "Just drag the Install app, or Install app image, or Install ESD image onto the top, **hit** start and enjoy."
I suggest you use "click".
2." If you use Chameleon Bootloader, you can drop your Chameleon Extra folder onto the /Extra lable to make this **an** Chameleon **bootabale** image."
Should be "a" & "bootable".  :)
3."the precompiled binary could be downloaded at the **realease** page."
Should be "release".
4. "This is an simple app that **automaticly** modifies the OS X Installation app/disk image so that it could be used as a Hackintosh image and install OS X on non-apple computers."
Should be "automatically".
5. "and I'm pretty confident it's **convertable**."
Should be "convertible".
6. "What I'm expecting **is** that turning this into a shell script would fix the authoriation problem."
"Is" should be deleted.
7. As I said @PCBETA, could you upload a precompiled version of the latest release on your main code so that I can merge yours & mine in a script that users can get the latest version directly? Thanks.

And unfortunately, tomorrow I will go back to school, maybe I can reply on next weekends... Oops.

// 英文渣的要死最近 凑合看吧。。

**Comment by arslan2012** [comment]
都改了，我的Github上几乎全是typo，我一直以为没人会看，XD,所以没管，给你发了个Collaborator invitation，你加进来吧

**Comment by PMheart** [comment]
ok seen

**Comment by PMheart** [comment]
额。。那个东西在哪里 好吧我很少玩github

**Comment by PMheart** [comment]
已加入。
不过我又不懂swift的。。

**Comment by arslan2012** [comment]
哈哈，不用懂Swift，你不是都会改语言内容了嘛，够了。而且我的程序就是用swift给你的脚本加了个壳子而已，批处理内核在BatchProcessAPI.swift里面，你绝对能看懂

**Comment by PMheart** [comment]
额。。好吧 一会儿看看 另外release page的下载链接怎么抓取 方便curl

**Comment by arslan2012** [comment]
这个应该对你有用，你试试？除了第一个答案剩下都是用curl的方法。
https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo

**Comment by PMheart** [comment]
有点乱了。。
这样 我直接在你的repo下upload个latest zip
而且国内amazonaws貌似是被xx的

**Comment by arslan2012** [comment]
这样也挺好的，我看XX-NET他们也是在repo下建个zip和[下载链接](https://github.com/XX-net/XX-Net/blob/master/code/default/download.md)
额。。。但是如果被墙的话，岂不是还得我们自己搬运？

**Comment by PMheart** [comment]
嗯。。
但是github没被墙 所以在你的repo下获取ok的 我在论坛发脚本了 你可以看看 一键获取最新版

**Comment by arslan2012** [comment]
哈哈，不错，看到了

**Comment by PMheart** [comment]
:-)
我更新了下 下载ok以后自动打开目录 并且改为command后缀(因为貌似 .sh 无法直接Terminal运行)

**Comment by arslan2012** [comment]
seen 😋

**Comment by PMheart** [comment]
好了我可能要offline了...
另外可以加个Telegram什么的咩😀

**Comment by arslan2012** [comment]
Telegram?我长这么大还没见人用过电报哎...

**Comment by PMheart** [comment]
额。。一个app 算是Social Networking类的app 只不过QQ最近越来越少用

**Comment by arslan2012** [comment]
哦，好，那我现在下一个

**Comment by PMheart** [comment]
话说你有用FB的咩

**Comment by arslan2012** [comment]
有啊

**Comment by arslan2012** [comment]
telegram我也装上了，然而并不知道怎么用？手机号就是账户名？

**Comment by PMheart** [comment]
嗯 是的
@ 也可以当用户名
