### ISSUE TITLE
1.0(83)

### ISSUE THREAD

**Issue by jackacc** [arslan2012/Lazy-Hackintosh-Image-Generator#10]
![QQ20190321-013008](https://user-images.githubusercontent.com/43131867/54706208-4ad35280-4b79-11e9-8a3d-64ce97453988.png)
![QQ20190321-013037](https://user-images.githubusercontent.com/43131867/54706210-4ad35280-4b79-11e9-871d-8675dd2af2d7.png)
.

**Comment by jackacc** [comment]
![1](https://user-images.githubusercontent.com/43131867/54706619-4ce9e100-4b7a-11e9-91e4-33be6bc6fb4a.png)
![Uploading 2.png…]()

**Comment by arslan2012** [comment]
已修复,请尝试新版
