### ISSUE TITLE
[BUG]运行软件点击开始无反应

### ISSUE THREAD

**Issue by yflwz** [arslan2012/Lazy-Hackintosh-Image-Generator#11]
下载https://raw.githubusercontent.com/arslan2012/Lazy-Hackintosh-Image-Generator/master/LazyHackintoshGenerator.app.zip之后，在mac10.13.5系统上运行，拖安装镜像或文件过去，点开始提示『清理更新建文件夹』后无反应。

**Comment by yflwz** [comment]
本来还想着输出日志上传的，结果日志也没有生成

**Comment by arslan2012** [comment]
提示你输密码的时候你输密码了吗？

**Comment by yflwz** [comment]
输入了

**Comment by arslan2012** [comment]
那就应该会有日志的

**Comment by yflwz** [comment]
日志也生成不了，没有日志文件呢。还是说需要什么运行环境呢？

**Comment by coderdream** [comment]
![image](https://user-images.githubusercontent.com/1549511/55288837-f8532b00-53ef-11e9-92ee-9fe7123d6599.png)
10.14.4版，一直都在等待中

**Comment by coderdream** [comment]
` 8 -rw-r--r--  1 coderdream  wheel    321  3 31 20:04 tech.arslan2012.lazy.log
CoderDreamdeiMac:tmp coderdream$ cat tech.arslan2012.lazy.log 
[20:0:58]: Helper: Bundle Version => 1.0.0
[20:1:0]: Helper: Installed Version => 1.0.0
[20:1:32]: =======Workflow Starting======
[20:1:32]: 7.15,true,false,,,
[20:4:14]: Helper: Bundle Version => 1.0.0
[20:4:14]: Helper: Installed Version => 1.0.0
[20:4:35]: =======Workflow Starting======
[20:4:35]: 7.15,true,false,,, `

**Comment by arslan2012** [comment]
@CoderDream 非常感谢, 找到问题了, 已修复并发布新版
