### ISSUE TITLE
[BUG]10.13.6和10.14下没反应

### ISSUE THREAD

**Issue by bullscow** [arslan2012/Lazy-Hackintosh-Image-Generator#14]
把 install xxx.app或者 .dmg 拖放成功后，drop kernel 或者 generator cdr不管勾选与否，点击start都是无反应，不知道是不是刚好我用的都是懒人版的系统。

**Comment by arslan2012** [comment]
@PMheart 在吗?求救, XPC 服务在10.13.6上根本没有启动.同一个程序放到10.15上啥问题没有. 我没找到问题在哪儿, 是系统有什么区别吗?

**Comment by PMheart** [comment]
10.13 的事情... 不记得了啦 sorry

**Comment by bullscow** [comment]
但在10.15.1下运行正常。
