### ISSUE TITLE
[Feature]我看当前master已经可以支持10.15了，可否release一个版本啊

### ISSUE THREAD

**Issue by wildfire810** [arslan2012/Lazy-Hackintosh-Image-Generator#15]
不然的话用户不是还得自己编译swift什么的嘛

**Comment by arslan2012** [comment]
https://raw.githubusercontent.com/arslan2012/Lazy-Hackintosh-Image-Generator/master/LazyHackintoshGenerator.app.zip

**Comment by wildfire810** [comment]
非常感谢。前几年咱们还聊过几句呢
:)
你可能不记得了
