### ISSUE TITLE
Does this work Clover?

### ISSUE THREAD

**Issue by 9Morello** [arslan2012/Lazy-Hackintosh-Image-Generator#2]
And if so, whats the correct procedure to install it? Should I put anything on the image generator?

**Comment by arslan2012** [comment]
If you're using Clover it should be easier to just use the original image
[USB Installer with Clover](http://www.insanelymac.com/forum/topic/307003-clover-os-x-el-capitan-usb/)
If you're using MBR partition map you may wanna using my app to alter it and check the MBR patch check box.
And no you don't need to put anything else in the generator, the installer app/dmg is all you needed.

**Comment by 9Morello** [comment]
Thanks for the attention. I managed to install it in a MBR partition, without having to format it all. I used your image with clover and it worked great. El Capitan is up and running.
