### ISSUE TITLE
mac10.12.2失败

### ISSUE THREAD

**Issue by ju0632** [arslan2012/Lazy-Hackintosh-Image-Generator#5]
=======Workflow Starting======
/Applications/Install macOS Sierra.app,7.15,true,false,false,true,false,,,,

**Comment by ju0632** [comment]
若开启排错模式 则 停留在等待asr命令执行完毕 状态很长时间

**Comment by arslan2012** [comment]
已知Bug，必须开启排错模式才能使用。因为暂时没有编程环境，可能一两个星期之后才能修复。

开启排错模式之后,

停滞在asr命令很有可能是镜像卸载失败引起的，卸载所有已挂载镜像，运行 rm -rf /tmp/com.pcbeta.lazy然后重启系统即可。

**Comment by arslan2012** [comment]
必须开启排错模式的Bug已经在 d0b3518a36b901fef0967792b19e6a6530bd32da 修复，测试软件之后，预计今天晚上更新软件

**Comment by PMheart** [comment]
应该不需要 `rm -rf /tmp/com.pcbeta.lazy` 的。
/tmp 下的东西重启以后会自己清除。
