### ISSUE TITLE
制作10.12.4镜像时崩溃

### ISSUE THREAD

**Issue by wildfire810** [arslan2012/Lazy-Hackintosh-Image-Generator#6]
在拷贝打包文件夹到/system/installation...的时候
版本2.0（64）

launch path not accessible

**Comment by arslan2012** [comment]
请贴出详细Bug说明或者排错日志

**Comment by arslan2012** [comment]
@PMheart 10.12.4的制作方法有什么变化么？

**Comment by wildfire810** [comment]
首先系统升级到10.12.4，LazyHacking升级到2.0（64），然后用dmg制作镜像。点选了放入原版内核，其他留空。以前也是这个制作步骤。
然后在复制Package文件夹到/System/Installation的时候，弹出错误报告。崩溃原因是launch path not accessible，调用堆栈我没有复制出来。
我现在回滚到过去的系统版本，10.12.3，LazyHacking2.0（52），生成成功。
我可以继续测试10.12.4时LazyHacking2.0（52）可否成功，以及10.12.3时LazyHacking2.0（64）可否成功。

**Comment by arslan2012** [comment]
@wildfire810 软件打开之后，在菜单栏里面有个选项（就是屏幕最上面有小苹果的那个地方，旁边就是软件名） 开启调试日志，点开那个之后再生成就会在桌面上生成一个日志文件，把那个日志发过来，或者直接贴到这里。

**Comment by wildfire810** [comment]
=======Workflow Starting======
/Volumes/VMware Shared Folders/D/BaiduYunDownload/Install macOS Sierra 10.12.4 www.myjike.com.dmg,7.15,false,false,false,false,true,,,,
==========22:19:28==========
/bin/rm -rf /tmp/com.pcbeta.lazy,progress:0.0


==========22:19:28==========
/bin/mkdir /tmp/com.pcbeta.lazy,progress:3.0


========cleaning done========
==========22:19:30==========
/usr/bin/hdiutil attach /Volumes/VMware Shared Folders/D/BaiduYunDownload/Install macOS Sierra 10.12.4 www.myjike.com.dmg -noverify -nobrowse -quiet -mountpoint /tmp/com.pcbeta.lazy/OriginMount,progress:2.0


==========22:19:32==========
/usr/bin/hdiutil attach /tmp/com.pcbeta.lazy/OriginMount/Install macOS Sierra.app/Contents/SharedSupport/InstallESD.dmg -noverify -nobrowse -quiet -mountpoint /tmp/com.pcbeta.lazy/ESDMount,progress:2.0


=======mounting done========
==========22:19:51==========
/usr/bin/hdiutil create -size 7.15g -layout SPUD -ov -fs HFS+J -volname OS X Lazy Installer /tmp/com.pcbeta.lazy/Lazy Installer.dmg,progress:22.0
created: /tmp/com.pcbeta.lazy/Lazy Installer.dmg


==========22:19:52==========
/usr/bin/hdiutil attach /tmp/com.pcbeta.lazy/Lazy Installer.dmg -noverify -nobrowse -quiet -mountpoint /tmp/com.pcbeta.lazy/LazyMount,progress:2.0


=======creating done========
==========22:20:25==========
sudo /usr/sbin/asr restore --source /tmp/com.pcbeta.lazy/ESDMount/BaseSystem.dmg --target /tmp/com.pcbeta.lazy/LazyMount --erase --format HFS+ --noprompt --noverify
==========22:20:25==========
/usr/bin/hdiutil detach /Volumes/OS X Base System -force,progress:0.0
"disk3" unmounted.
"disk3" ejected.


==========22:20:27==========
/usr/bin/hdiutil attach /tmp/com.pcbeta.lazy/Lazy Installer.dmg -noverify -nobrowse -quiet -mountpoint /tmp/com.pcbeta.lazy/LazyMount,progress:0.0


Detected System Version:10.12.4 16E195
===========================
==========22:20:27==========
sudo /usr/sbin/diskutil rename OS X Base System Sierra Custom Installer
==========22:20:27==========
/bin/cp /tmp/com.pcbeta.lazy/ESDMount/BaseSystem.chunklist /tmp/com.pcbeta.lazy/LazyMount,progress:2.0


==========22:20:41==========
/bin/cp /tmp/com.pcbeta.lazy/ESDMount/BaseSystem.dmg /tmp/com.pcbeta.lazy/LazyMount,progress:2.0


==========22:20:41==========
/bin/cp /tmp/com.pcbeta.lazy/ESDMount/AppleDiagnostics.chunklist /tmp/com.pcbeta.lazy/LazyMount,progress:2.0


==========22:20:41==========
/bin/cp /tmp/com.pcbeta.lazy/ESDMount/AppleDiagnostics.dmg /tmp/com.pcbeta.lazy/LazyMount,progress:2.0


==========22:20:42==========
/bin/rm -rf /tmp/com.pcbeta.lazy/LazyMount/System/Installation/Packages,progress:2.0


==========22:22:40==========
sudo /bin/cp -R /tmp/com.pcbeta.lazy/ESDMount/Packages /tmp/com.pcbeta.lazy/LazyMount/System/Installation
==========22:22:40==========
/bin/mkdir /tmp/com.pcbeta.lazy/LazyMount/System/Library/Kernels,progress:1.0


========copying done========

希望有帮助，只有2.0(64)有错，2.0(52)没错

**Comment by wildfire810** [comment]
顺便说一句，现在pcbeta这样了，大家是改hosts，还是到什么别的地方交流了？

**Comment by arslan2012** [comment]
@wildfire810 会英语就去insanelymac,不会的话就改host

**Comment by wildfire810** [comment]
好嘞。顺便问一句。远景为什么弄成这样了？原本不是还挂广告商业化什么的呢？

**Comment by arslan2012** [comment]
远景和景腾公司之间就是个挂名，没什么关系。

所以远景的备案也不是景腾备的，是网站站长用自己的身份证备的个人备案。

结果现在被发现了，人家就不给他备案了。。。。。。。

**Comment by wildfire810** [comment]
多谢。那个。刚才的bug反馈能看出是什么问题吗？我自己也搞开发的，如果你需要更高难度的测试，相信我也搞得定。

**Comment by arslan2012** [comment]
bug反馈看不出是什么问题，我先比较一下52和64的代码区别。如果再找不到问题我再来找你帮忙。多谢合作.

**Comment by wildfire810** [comment]
客气了。你们开放出来生产力工具，才是方便了所有人

**Comment by wildfire810** [comment]
客气了。你们开放出来生产力工具，才是方便了所有人

**Comment by arslan2012** [comment]
很有可能是lvzn二进制文件缺失了可执行权限导致的.
测试1：不要点选放入内核，执行一次。
如果测试1没出问题
测试2:（通过右键显示包内容）把52的/contents/resources/lvzn复制到64的相同路径下
如果测试2没出问题
测试3:从GitHub上重新下载最新的包https://github.com/arslan2012/Lazy-Hackintosh-Image-Generator/commit/c60a8cd40e81178204d1e022b80f2d8c09d1be64

**Comment by wildfire810** [comment]
1非常快的完成了。
2我想更新64版，但是现在更新出来是66版

结果是66版可以正常放入内核并生成镜像

**Comment by arslan2012** [comment]
恩，对，那就是已经解决了，66是我改完你这个Bug之后放上去的。

**Comment by wildfire810** [comment]
多谢。可以结案了。

**Comment by PMheart** [comment]
@arslan2012 Oops... Yes.
这样吧，把所有
`perl -pi -e 's|\\xE8\\x25\\x00\\x00\\x00\\xEB\\x05\\xE8`
开头的 patches (目前是)
`        if !self.SystemVersion.SysVerBiggerThan("10.11") {
            /////// 10.10.x
            Command("/bin/sh",["-c","perl -pi -e 's|\\xE8\\x25\\x00\\x00\\x00\\xEB\\x05\\xE8\\xCE\\x02\\x00\\x00|\\xE8\\x25\\x00\\x00\\x00\\x90\\x90\\xE8\\xCE\\x02\\x00\\x00|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)
        }else if self.SystemVersion.SysVerBiggerThan("10.11.99"){
            if self.SystemBuildVersion == "16A201w"{
                /////// 10.12.DB1.116A201w
                Command("/bin/sh",["-c","perl -pi -e 's|\\xC3\\x48\\x85\\xDB\\x74\\x71\\x48\\x8B\\x03\\x48\\x89\\xDF\\xFF\\x50\\x28\\x48|\\xC3\\x48\\x85\\xDB\\xEB\\x12\\x48\\x8B\\x03\\x48\\x89\\xDF\\xFF\\x50\\x28\\x48|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)
                Command("/bin/sh",["-c","perl -pi -e 's|\\xE8\\x25\\x00\\x00\\x00\\xEB\\x05\\xE8\\xCE\\x02\\x00\\x00|\\xE8\\x25\\x00\\x00\\x00\\x90\\x90\\xE8\\xCE\\x02\\x00\\x00|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)
            }else if self.SystemBuildVersion == "16A238m" || self.SystemBuildVersion == "16A239j"{
                /////// 10.12.PB1.16A238m, 10.12.DB2.16A239j
                Command("/bin/sh",["-c","perl -pi -e 's|\\xC3\\x48\\x85\\xDB\\x74\\x71\\x48\\x8B\\x03\\x48\\x89\\xDF\\xFF\\x50\\x28\\x48|\\xC3\\x48\\x85\\xDB\\xEB\\x12\\x48\\x8B\\x03\\x48\\x89\\xDF\\xFF\\x50\\x28\\x48|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)
                Command("/bin/sh",["-c","perl -pi -e 's|\\xE8\\x25\\x00\\x00\\x00\\xEB\\x05\\xE8\\x7E\\x05\\x00\\x00|\\xE8\\x25\\x00\\x00\\x00\\x90\\x90\\xE8\\x7E\\x05\\x00\\x00|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)
            }
        }else {
            //////// 10.11.x
            Command("/bin/sh",["-c","perl -pi -e 's|\\xC3\\x48\\x85\\xDB\\x74\\x70\\x48\\x8B\\x03\\x48\\x89\\xDF\\xFF\\x50\\x28\\x48|\\xC3\\x48\\x85\\xDB\\xEB\\x12\\x48\\x8B\\x03\\x48\\x89\\xDF\\xFF\\x50\\x28\\x48|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)
            Command("/bin/sh",["-c","perl -pi -e 's|\\xE8\\x25\\x00\\x00\\x00\\xEB\\x05\\xE8\\xCE\\x02\\x00\\x00|\\xE8\\x25\\x00\\x00\\x00\\x90\\x90\\xE8\\xCE\\x02\\x00\\x00|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)
        }`
把 `E8` 开头的patch 都改成
`Command("/bin/sh",["-c","perl -pi -e 's|\\xE8\\x25\\x00\\x00\\x00\\xEB\\x05\\xE8|\\xE8\\x25\\x00\\x00\\x00\\x90\\x90\\xE8|g' \(self.lazypath)/System/Library/Kernels/kernel"], "#COPYKERNELF#",0)`

也就是删掉一些多余的 bytes 。这样就可以把 10.10.x 10.11.x 10.12.x 统一，并且已确定不会出问题。

**Comment by arslan2012** [comment]
@PMheart 求改掉commit一下😟，其他的我自己来。

**Comment by PMheart** [comment]
@arslan2012 Well. Committed.
