### ISSUE TITLE
等待asr命令执行完毕

### ISSUE THREAD

**Issue by wildfire810** [arslan2012/Lazy-Hackintosh-Image-Generator#7]
vmware上运行10.12.5，宿主是win10 64bit。升级10.12.5之前都可以正确制作镜像。
当前是使用从appstore下载的10.12.5升级文件，制作.cdr。
等待asr命令失败，让我检查cpu占用率。打开活动监视器，未察觉到大的资源占用，也未发现有asr字样的进程。

**Comment by njzydark** [comment]
跟你一样的问题，你解决了吗？准备用这个给10.13打mbr补丁。。。

**Comment by arslan2012** [comment]
我似乎有些头绪了，你们俩是不是都直接用的.app后缀的文件？
@wildfire810 @0njzy0

**Comment by PMheart** [comment]
提示：似乎从 10.13 开始，无法再修改 MBR 补丁了，否则会引发 OSInstall.mpkg 错误，导致系统无法安装。

**Comment by wildfire810** [comment]
我有可能用的.app。从store下载的。
以前都习惯用.dmg。是需要对.app二次解包吗？
顺便说一句，可能现在主要得面对10.13了吧。我主要给虚拟机用，生成.cdr，放官方原始内核就可以。但是现在vmware肯定做不到苹果文件系统（不能引导），我用10.12不更新文件系统，倒是可以升级上去运行起来。
需要我测什么，我配合你们

**Comment by arslan2012** [comment]
@wildfire810 我正在本机测，10.13变化有点大，软件需要升级的地方也挺多，而且我还要上班，可能要点时间才能更新app了

**Comment by wildfire810** [comment]
更新什么的我不会催的。我是蛮珍惜这个项目的。希望你们能愉快的发展下去这个小工具。10.13未来怎么做，等正式版发了再决定也不迟。黑苹果用的引导工具链似乎已经有人更新了可以用

**Comment by nsxz945** [comment]
哈哈 看到有比较新的讨论 感觉很棒 支持一下

**Comment by arslan2012** [comment]
10.13没有思路了╮(╯_╰)╭。似乎要大改软件。准备等正式版出来。。。实在不行就再给10.13写个新的软件.。。

**Comment by wildfire810** [comment]
那我等你好消息了：）记得通知我

**Comment by PMheart** [comment]
Hi. 不得不说这次 10.13 变化得很复杂，而且也无法做到所有人通用了。（做好的 dmg 因 UUID 等不同，无法通用）
http://bbs.pcbeta.com/viewthread-1746351-1-1.html
这是我 po 的文，对比先前就知道，10.13 全新的文件结构很复杂......

**Comment by wildfire810** [comment]
苹果文件系统的话，怎么做？另外，我是想给虚拟机装osx，会变成什么样？
--

**Comment by ju0632** [comment]
不知道作者是否找的思路
还有更新的打算吗

**Comment by arslan2012** [comment]
10.13完全改变了安装包的结构,已经没法更新了.
要支持10.13的话只能从头开始重新写.

**Comment by ju0632** [comment]
@arslan2012 首先谢谢你的无私奉献，不知作者是否还有时间和精力去重写 随缘吧 更就用不更就用旧版了 不用10.13了
