### ISSUE TITLE
10.14.4

### ISSUE THREAD

**Issue by jackacc** [arslan2012/Lazy-Hackintosh-Image-Generator#8]
[Lazy log.txt](https://github.com/arslan2012/Lazy-Hackintosh-Image-Generator/files/2948099/Lazy.log.txt)

**Comment by PMheart** [comment]
Hi,

Yes, Apple has slightly changed the name of BaseSystem (OS X Base System -> macOS Base System) under 10.14.4. It's kind of easy to fix it up.

As you see, it's hardcoded in https://github.com/arslan2012/Lazy-Hackintosh-Image-Generator/blob/master/LazyHackintoshGenerator/Copy.swift#L14 and https://github.com/arslan2012/Lazy-Hackintosh-Image-Generator/blob/master/LazyHackintoshGenerator/Copy.swift#L34. So simply adding a check would do the trick I guess. Unfortunately I don't have the secret key from @arslan2012 and thus cannot produce a new binary to test.

**Comment by arslan2012** [comment]
I'm really sorry I just saw this now, I had a really shitty and busy weekend.

fix it in [#ef52284](https://github.com/arslan2012/Lazy-Hackintosh-Image-Generator/commit/ef52284b14ef37cefda2f63ea87e8e72a40c30d6)

If you need it, I can give the key to you @PMheart .

**Comment by PMheart** [comment]
Good, thanks a lot @arslan2012 !

No, I don't think I need it, at least for now. :)
